export const signIn = async (email, password) => {
  try {
    console.log(email);
  } catch (error) {
    console.log('Error inside signin method', error);
  }
};
